// Package config provides a format-preserving parser and writer for
// ~/.ssh/config-style files: comments, blank lines, indentation, and any
// directive not explicitly touched by an operation round-trip byte-for-byte.
package config

import (
	"os"
	"strings"
)

// Config is a parsed ssh_config file.
type Config struct {
	Nodes []Node

	// Indent is the most common leading-whitespace prefix seen across all
	// directive lines in the file. It's only consulted when generating a
	// brand new line this run (new host, or a new key with no prior line in
	// its block) — existing lines always keep their own original indent.
	Indent string

	// HadTrailingNewline records whether the original file ended with "\n",
	// so Serialize reproduces the same convention rather than silently
	// adding or dropping a trailing newline.
	HadTrailingNewline bool
}

// Node is a top-level element of the file: either an opaque RawLine
// (preamble content before the first Host block — comments, blanks, or bare
// global directives, all left untouched by this app) or a *HostBlock.
type Node interface{ isNode() }

// RawLine is an unparsed top-level line, kept verbatim.
type RawLine struct{ Text string }

// HostBlock is one "Host <alias...>" block and everything until the next
// Host line or EOF.
type HostBlock struct {
	// HostLineRaw is the exact original "Host ..." line text, sans any
	// trailing "# comment" portion.
	HostLineRaw string
	// HostLineComment is the trailing comment on the Host line itself
	// (including the leading "#"), or "" if none.
	HostLineComment string
	// Alias is the literal whole remainder after "Host ", verbatim
	// (including internal spacing), e.g. "foo bar *.example.com" or "*".
	// This is the block's identity for lookup, matching sshconf semantics.
	Alias string
	// Patterns is strings.Fields(Alias) — a convenience split, never used
	// for identity/lookup.
	Patterns []string
	// Lines holds every line between the Host line and the next block (or
	// EOF), in original order.
	Lines []BlockLine
}

// BlockLine is either a raw comment/blank line interior to a block, or a
// structured Directive.
type BlockLine interface{ isBlockLine() }

// BlockRawLine is a comment or blank line inside a Host block, kept verbatim.
type BlockRawLine struct{ Text string }

// Directive is one parsed "Key value" (or "Key=value") line inside a block.
type Directive struct {
	// Key is the directive name in its original case as first written.
	Key string
	// Value is the trimmed remainder after the key/separator.
	Value string
	// Comment is the trailing "# ..." comment on this line, if any
	// (including the leading "#"), preserved across value edits so an
	// UpdateHost call doesn't silently drop it.
	Comment string
	// Raw is the exact original line text (indent + key + sep + value +
	// trailing comment). Printed verbatim unless this specific line is
	// regenerated by an operation this run.
	Raw string
}

func (RawLine) isNode()           {}
func (*HostBlock) isNode()        {}
func (BlockRawLine) isBlockLine() {}
func (*Directive) isBlockLine()   {}

const defaultIndent = "  "

// Parse reads and parses an ssh_config-style file at path. A missing file is
// not an error: it yields an empty Config, matching the "no ~/.ssh/config
// yet" case.
func Parse(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &Config{Indent: defaultIndent, HadTrailingNewline: true}, nil
	}
	if err != nil {
		return nil, err
	}
	return ParseString(string(data)), nil
}

// ParseString parses ssh_config-style text already in memory.
func ParseString(data string) *Config {
	if data == "" {
		return &Config{Indent: defaultIndent, HadTrailingNewline: false}
	}

	hadTrailingNewline := strings.HasSuffix(data, "\n")
	text := data
	if hadTrailingNewline {
		text = text[:len(text)-1]
	}
	lines := strings.Split(text, "\n")

	cfg := &Config{HadTrailingNewline: hadTrailingNewline}
	var current *HostBlock

	// pending buffers blank/comment lines seen since the last committed
	// directive in the current block. Whether they're interior to the
	// block (if another directive in the same block follows) or actually
	// belong between blocks (if a new Host line or EOF comes next instead)
	// can't be known until the next line is seen, so the decision is
	// deferred until then.
	var pending []BlockRawLine

	flushPendingAsTopLevel := func() {
		for _, p := range pending {
			cfg.Nodes = append(cfg.Nodes, RawLine{Text: p.Text})
		}
		pending = nil
	}

	for _, line := range lines {
		line = strings.TrimSuffix(line, "\r")

		key, value, isDirective := tokenizeLine(line)

		if isDirective && strings.EqualFold(key, "host") {
			flushPendingAsTopLevel()
			code, comment := splitTrailingComment(line)
			block := &HostBlock{
				HostLineRaw:     strings.TrimRight(code, " \t"),
				HostLineComment: comment,
				Alias:           value,
				Patterns:        strings.Fields(value),
			}
			cfg.Nodes = append(cfg.Nodes, block)
			current = block
			continue
		}

		if current == nil {
			cfg.Nodes = append(cfg.Nodes, RawLine{Text: line})
			continue
		}

		if isDirective {
			for _, p := range pending {
				current.Lines = append(current.Lines, p)
			}
			pending = nil
			_, comment := splitTrailingComment(line)
			current.Lines = append(current.Lines, &Directive{Key: key, Value: value, Comment: comment, Raw: line})
		} else {
			pending = append(pending, BlockRawLine{Text: line})
		}
	}
	flushPendingAsTopLevel()

	cfg.Indent = computePopularIndent(cfg)
	return cfg
}

// computePopularIndent returns the most common leading-whitespace prefix
// across all Directive lines in the file, defaulting to two spaces if there
// are none to sample.
func computePopularIndent(cfg *Config) string {
	counts := map[string]int{}
	for _, n := range cfg.Nodes {
		block, ok := n.(*HostBlock)
		if !ok {
			continue
		}
		for _, bl := range block.Lines {
			d, ok := bl.(*Directive)
			if !ok {
				continue
			}
			counts[leadingWhitespace(d.Raw)]++
		}
	}
	best, bestCount := defaultIndent, 0
	for indent, count := range counts {
		if count > bestCount {
			best, bestCount = indent, count
		}
	}
	return best
}

func leadingWhitespace(s string) string {
	i := 0
	for i < len(s) && (s[i] == ' ' || s[i] == '\t') {
		i++
	}
	return s[:i]
}

// splitTrailingComment splits a raw line into its code portion and trailing
// "# comment" portion (comment includes the leading "#", or is "" if none).
func splitTrailingComment(line string) (code, comment string) {
	idx := strings.IndexByte(line, '#')
	if idx == -1 {
		return line, ""
	}
	return line[:idx], line[idx:]
}

// Serialize renders the Config back to text, byte-for-byte identical to the
// original input for any content not touched by an operation this run.
func (c *Config) Serialize() string {
	var b strings.Builder
	for i, n := range c.Nodes {
		if i > 0 {
			b.WriteByte('\n')
		}
		switch node := n.(type) {
		case RawLine:
			b.WriteString(node.Text)
		case *HostBlock:
			b.WriteString(node.HostLineRaw)
			b.WriteString(node.HostLineComment)
			for _, bl := range node.Lines {
				b.WriteByte('\n')
				switch line := bl.(type) {
				case BlockRawLine:
					b.WriteString(line.Text)
				case *Directive:
					b.WriteString(line.Raw)
				}
			}
		}
	}
	if c.HadTrailingNewline && len(c.Nodes) > 0 {
		b.WriteByte('\n')
	}
	return b.String()
}
